//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_NewSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose leftpose
        {
            get
            {
                return SteamVR_Actions.newSet_leftpose;
            }
        }
        
        public virtual SteamVR_Action_Boolean lefttrigger
        {
            get
            {
                return SteamVR_Actions.newSet_lefttrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean righttrigger
        {
            get
            {
                return SteamVR_Actions.newSet_righttrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean rightgrip
        {
            get
            {
                return SteamVR_Actions.newSet_rightgrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftgrip
        {
            get
            {
                return SteamVR_Actions.newSet_leftgrip;
            }
        }
        
        public virtual SteamVR_Action_Vector2 leftstick
        {
            get
            {
                return SteamVR_Actions.newSet_leftstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean leftmenu
        {
            get
            {
                return SteamVR_Actions.newSet_leftmenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean rightmenu
        {
            get
            {
                return SteamVR_Actions.newSet_rightmenu;
            }
        }
        
        public virtual SteamVR_Action_Pose rightpose
        {
            get
            {
                return SteamVR_Actions.newSet_rightpose;
            }
        }
        
        public virtual SteamVR_Action_Boolean rc_up
        {
            get
            {
                return SteamVR_Actions.newSet_rc_up;
            }
        }
        
        public virtual SteamVR_Action_Boolean rc_down
        {
            get
            {
                return SteamVR_Actions.newSet_rc_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean rc_left
        {
            get
            {
                return SteamVR_Actions.newSet_rc_left;
            }
        }
        
        public virtual SteamVR_Action_Boolean rc_right
        {
            get
            {
                return SteamVR_Actions.newSet_rc_right;
            }
        }
        
        public virtual SteamVR_Action_Boolean ls_push
        {
            get
            {
                return SteamVR_Actions.newSet_ls_push;
            }
        }
    }
}
